=== em411/pelagos/web/schema/dataset_registry/dataset_registry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="dataset_registry">
        <xs:annotation>
            <xs:documentation>The root element represents a list of dataset registry entries.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="entry"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="entry">
        <xs:annotation>
            <xs:documentation>This element represents one dataset registry entry.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="registration_user"/>
                <xs:element ref="dataset"/>
                <xs:element ref="access_control"/>
                <xs:element ref="transport" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" use="optional" type="xs:NMTOKEN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="registration_user" type="user_TYPE">
        <xs:annotation>
            <xs:documentation>This is the user who is taking responsibility for this registry entry. This is not necessarily the owner or originator of the dataset, but the individual responsible for registering the dataset with GRIIDC.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="user_TYPE">
        <xs:annotation>
            <xs:documentation>Additional identifying information (e.g. first and last name) may be included within the element, but the id attribute is what will be used to identify the user.</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" use="required" type="xs:positiveInteger">
                    <xs:annotation>
                        <xs:documentation>This is the user's id number from RPIS.</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="dataset">
        <xs:annotation>
            <xs:documentation>This element represents a dataset.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="source"/>
                <xs:element ref="title"/>
                <xs:element ref="abstract"/>
                <xs:element ref="doi" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="sequence" use="optional" type="xs:integer">
                <xs:annotation>
                    <xs:documentation>This is the sequence number for the dataset. This can be assigned by the user at regsitration, but must be unique for all datasets for a given DIF. If omitted during registration, a sequence number will be automatically assigned. The sequence number is required to update a previous registration entry.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="udi" use="optional" type="xs:NMTOKEN">
                <xs:annotation>
                    <xs:documentation>This is the unique dataset identifier (udi) for the dataset. This should be omitted during registration as it is automatically generated by the system.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="source">
        <xs:annotation>
            <xs:documentation>This element represent the dataset source. The sub-element that is required depends on the dataset source type. For GoMRI datasets, the funding_cyle element should be used. For external (historical) datasets, the external_repository element should be used.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice>
                <xs:element ref="funding_cycle"/>
                <xs:element ref="external_repository"/>
            </xs:choice>
            <xs:attribute name="type" use="required" type="source_TYPE">
                <xs:annotation>
                    <xs:documentation>This specifies the source type and should be one of: gomri, external</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="source_TYPE">
        <xs:restriction base="xs:string">
            <xs:enumeration value="gomri"/>
            <xs:enumeration value="external"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="funding_cycle">
        <xs:annotation>
            <xs:documentation>This element represents a funding cycle, e.g. RFPI, RFPII, etc.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="project"/>
            </xs:sequence>
            <xs:attribute name="reference" use="required" type="funding_cycle_reference_TYPE">
                <xs:annotation>
                    <xs:documentation>This is the reference id for the funding cycle for this dataset. It should be, e.g., R01 (RFPI), R02 (RFP2), B01 (Year One Block Grant 1)</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="funding_cycle_reference_TYPE">
        <xs:restriction base="xs:string">
            <xs:pattern value="(B|R)\d\d"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="project">
        <xs:annotation>
            <xs:documentation>This element represents a GoMRI project.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="task"/>
            </xs:sequence>
            <xs:attribute name="sequence" use="required" type="xs:positiveInteger">
                <xs:annotation>
                    <xs:documentation>This is the sequence number of the project for this dataset within the funding cycle.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="task">
        <xs:annotation>
            <xs:documentation>This element represents a GoMRI task.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dif"/>
                <xs:element ref="originator"/>
                <xs:element ref="point_of_contact"/>
            </xs:sequence>
            <xs:attribute name="sequence" use="required" type="xs:nonNegativeInteger">
                <xs:annotation>
                    <xs:documentation>This is the sequence number of the task for this dataset within the project.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="dif">
        <xs:complexType>
            <xs:attribute name="sequence" use="required" type="xs:integer">
                <xs:annotation>
                    <xs:documentation>This is the sequence number of the dif for this dataset within the task.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="originator" type="user_TYPE">
        <xs:annotation>
            <xs:documentation>This is the individual who created the dataset.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="point_of_contact" type="user_TYPE">
        <xs:annotation>
            <xs:documentation>This is the individual who will serve as the point of contact for requests for information about this dataset.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="external_repository">
        <xs:annotation>
            <xs:documentation>This element represents an external (non-GoMRI) data repository.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="submitted_by"/>
            </xs:sequence>
            <xs:attribute name="reference" use="required" type="xs:integer">
                <xs:annotation>
                    <xs:documentation>This is a reference id for the extrenal repository.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="submitted_by">
        <xs:annotation>
            <xs:documentation>This element represents the individual who submitted data to the external repository.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:attribute name="reference" use="required" type="xs:integer">
                <xs:annotation>
                    <xs:documentation>This is a reference to identifying information about the individual who submitted data to the external repository.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="title" type="xs:string">
        <xs:annotation>
            <xs:documentation>This is the title of the dataset.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="abstract" type="xs:string">
        <xs:annotation>
            <xs:documentation>This is the abstract for the dataset.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="doi">
        <xs:annotation>
            <xs:documentation>This element represents the digital object identifier for the dataset. It is also used to request a doi be autogenerated.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="autogenerate" use="required" type="xs:boolean">
                        <xs:annotation>
                            <xs:documentation>Setting this to true will request a doi to be generated once the dataset becomes available.</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="access_control">
        <xs:annotation>
            <xs:documentation>This element represents the access control for a dataset.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="authorized_users" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="restricted" use="required" type="xs:boolean">
                <xs:annotation>
                    <xs:documentation>Setting this to true will restrict access to the dataset to the registration_user, originator, point_of_contact, and any additional users specified in the authorized_users element.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:element name="authorized_users">
        <xs:annotation>
            <xs:documentation>This element represents a list of users authorized to access this dataset (in addition to the registration_user, originator, and point_of_contact).</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="user" type="user_TYPE"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="transport">
        <xs:annotation>
            <xs:documentation>This element represents the transport mechanism used to move data to GRIIDC.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="data_url"/>
                <xs:element ref="metadata_url"/>
                <xs:element ref="pull" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="method" use="required" type="transport_method_TYPE">
                <xs:annotation>
                    <xs:documentation>This is the method that will be used for transport, e.g., http, ftp, sftp, etc.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="pull" use="required" type="xs:boolean">
                <xs:annotation>
                    <xs:documentation>If the transport method is a "push" method (such as sftp) this should be set to false. It may also be set to false if the source data is archived in a cyber-infrastructure that can be maintained in the next decade. If unsure, set this to true.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="transport_method_TYPE">
        <xs:restriction base="xs:string">
            <xs:enumeration value="http"/>
            <xs:enumeration value="ftp"/>
            <xs:enumeration value="sftp"/>
            <!--
            these methods are not yet available
            <xs:enumeration value="tds"/>
            <xs:enumeration value="erdap"/>
            -->
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="data_url" type="xs:anyURI">
        <xs:annotation>
            <xs:documentation>This is the URL pointing to the data file for this dataset. For "push" methods, this is a file URL (e.g. file:///sftp/path/to/data/file).</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="metadata_url" type="xs:anyURI">
        <xs:annotation>
            <xs:documentation>This is the URL pointing to the metadata file for this dataset. For "push" methods, this is a file URL (e.g. file:///sftp/path/to/metadata/file).</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="pull">
        <xs:annotation>
            <xs:documentation>This element contains information on when to initiate pull requests. This allows scheduling of data pulls during times of minimal network traffic and ability to register a dataset before it is available.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="available_date"/>
                <xs:element ref="start_time" minOccurs="0"/>
                <xs:element ref="start_days" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="available_date" type="xs:date">
        <xs:annotation>
            <xs:documentation>This is the date from which the dataset and metadata will be available at the specified data_url and metadata_url. The date is specified using the ISO 8601 date specification (YYYY-MM-DD).</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="start_time" type="xs:time">
        <xs:annotation>
            <xs:documentation>This is the time of day to begin pulling the dataset. Absence of this element will indicate that any time is acceptable. Time is specified in 24-hour time with seconds and a UTC offset for timezone. E.g., to specify 10 PM US Central Standard Time: 22:00:00-06:00</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="start_days">
        <xs:annotation>
            <xs:documentation>This element is used to indicate which days are acceptable for initiating the data pull. Absence of this element will indicate that any time is acceptable. If this element exists, all days of the week must be listed and the pull attribute must be set to true or false for each day.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:all>
                <xs:element name="Monday" type="day_TYPE"/>
                <xs:element name="Tuesday" type="day_TYPE"/>
                <xs:element name="Wednesday" type="day_TYPE"/>
                <xs:element name="Thursday" type="day_TYPE"/>
                <xs:element name="Friday" type="day_TYPE"/>
                <xs:element name="Saturday" type="day_TYPE"/>
                <xs:element name="Sunday" type="day_TYPE"/>
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="day_TYPE">
        <xs:attribute name="pull" use="required" type="xs:boolean"/>
    </xs:complexType>
</xs:schema>

=== em411/pelagos/web/schema/dataset_registry/dataset_registry_register.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset_registry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://data.gulfresearchinitiative.org/schema/dataset_registry/dataset_registry.xsd">
    <entry>
        <registration_user id="1"/>
        <dataset>
            <source type="gomri">
                <funding_cycle reference="R01">
                    <project id="1">
                        <task id="1">
                            <dif sequence="1"/>
                            <originator id="2"/>
                            <point_of_contact id="3"/>
                        </task>
                    </project>
                </funding_cycle>
            </source>
            <title>My Dataset Title</title>
            <abstract>My Dataset Abstract</abstract>
            <doi autogenerate="true"/>
        </dataset>
        <access_control restricted="true">
            <authorized_users>
                <user id="4"/>
                <user id="5"/>
                <user id="6"/>
            </authorized_users>
        </access_control>
        <transport method="http" pull="true">
            <data_url>http://www.myserver.org/path/to/data_file</data_url>
            <metadata_url>http://www.myserver.org/path/to/metadata_file</metadata_url>
            <pull>
                <available_date>2013-03-28</available_date>
                <start_time>01:00:00-06:00</start_time>
                <start_days>
                    <Monday pull="false"/>
                    <Tuesday pull="false"/>
                    <Wednesday pull="false"/>
                    <Thursday pull="false"/>
                    <Friday pull="false"/>
                    <Saturday pull="true"/>
                    <Sunday pull="true"/>
                </start_days>
            </pull>
        </transport>
    </entry>
</dataset_registry>

=== em411/pelagos/web/schema/dataset_registry/dataset_registry_register_min.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset_registry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://data.gulfresearchinitiative.org/schema/dataset_registry/dataset_registry.xsd">
    <entry>
        <registration_user id="1"/>
        <dataset>
            <source type="gomri">
                <funding_cycle reference="R01">
                    <project id="1">
                        <task id="1">
                            <dif sequence="1"/>
                            <originator id="2"/>
                            <point_of_contact id="3"/>
                        </task>
                    </project>
                </funding_cycle>
            </source>
            <title>My First Dataset Title</title>
            <abstract>My First Dataset Abstract</abstract>
        </dataset>
        <access_control restricted="false"/>
        <transport method="http" pull="true">
            <data_url>http://www.myserver.org/path/to/data_file_1</data_url>
            <metadata_url>http://www.myserver.org/path/to/metadata_file_1</metadata_url>
        </transport>
    </entry>
    <entry>
        <registration_user id="1"/>
        <dataset>
            <source type="gomri">
                <funding_cycle reference="R01">
                    <project id="1">
                        <task id="1">
                            <dif sequence="2"/>
                            <originator id="2"/>
                            <point_of_contact id="3"/>
                        </task>
                    </project>
                </funding_cycle>
            </source>
            <title>My Second Dataset Title</title>
            <abstract>My Second Dataset Abstract</abstract>
        </dataset>
        <access_control restricted="true"/>
        <transport method="http" pull="true">
            <data_url>http://www.myserver.org/path/to/data_file_2</data_url>
            <metadata_url>http://www.myserver.org/path/to/metadata_file_2</metadata_url>
        </transport>
    </entry>
</dataset_registry>
